parameters:
    librinfo:
        Librinfo\CoreBundle\Admin\AddressableAdmin:
            Sonata\AdminBundle\Form\FormMapper: # Form
                add:
                    General:
                        '':
                            name: ~
                            email: ~
                        Address:
                            address:
                                type: textarea
                                required: false
                            postalcode: ~
                            city: ~
                            country: ~
                    Specifics:
                        Communication:
                            description: ~
                        Email:
                            emailNpai: ~
                            emailNoNewsletter: ~
                        Address:
                            npai: ~
            Sonata\AdminBundle\Datagrid\ListMapper: # List
                add:
                    name: ~
                    email: ~
                    postalcode: ~
                    city: ~
                    country: ~
                    _action:
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper: # Filters
                add:
                    name: ~
                    address: ~
                    postalcode: ~
                    city: ~
                    country: ~
                    email: ~
                    npai: ~
                    emailNpai: ~
                    emailNoNewsletter: ~
            Sonata\AdminBundle\Show\ShowMapper:     # Show
                _copy: Sonata\AdminBundle\Form\FormMapper
        Librinfo\CoreBundle\Admin\UserAdmin:
            Sonata\AdminBundle\Form\FormMapper: # Form
                add:
                    General:
                        '':
                            username: ~
                            email: ~
                            plainPassword:
                                type: repeated
                                required: false
#                                    type: password
                                _options:
                                    translation_domain: FOSUserBundle
                                    first_options:
                                        label: form.password
                                    second_options:
                                        label: form.password_confirmation
                                        invalid_message: fos_user.password.mismatch
                            enabled:
                                required: false
                            locked:
                                required: false
                            last_login:
                                type: sonata_type_datetime_picker
                                required: false

#                            roles:
#                                type: sonata_type_immutable_array
                            credentials_expired:
                                type: checkbox
                                required: false
                    Groups:
                        '':
                            groups:
                                type: sonata_type_model
                                expanded: true
                                multiple: true
#                                auto_initialize: true
                                by_reference: true
                                required: false
            Sonata\AdminBundle\Datagrid\ListMapper: # List
                add:
                    username: ~
                    email: ~
                    enabled: ~
                    locked: ~
                    last_login:
                        type: datetime
                    roles:
                        type: array
                    credentials_expired:
                        type: boolean
                    credentials_expire_at:
                        type: datetime
                    _action:
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper: # Filters
                add:
                    username: ~
                    email: ~
                    enabled: ~
                    locked: ~
#                    last_login:
#                        type: datetime
#                    roles:
#                        type: array
#                    credentials_expire_at:
#                        type: datetime
            Sonata\AdminBundle\Show\ShowMapper:     # Show
                _copy: Sonata\AdminBundle\Form\FormMapper

        Librinfo\CoreBundle\Admin\GroupAdmin:
            Sonata\AdminBundle\Form\FormMapper: # Form
                add:
                    General:
                        '':
                            name: ~
#                            roles:
#                                type: sonata_type_immutable_array
                            users:
                                type: sonata_type_model
                                expanded: true
                                multiple: true
#                                auto_initialize: true
                                by_reference: false
                                required: false
#                                _options:
#                                    edit: inline
#                                    inline: table
            Sonata\AdminBundle\Datagrid\ListMapper: # List
                add:
                    name: ~
                    roles:
                        type: array
                    _action:
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper: # Filters
                add:
                    name: ~
#                    roles:
#                        type: array
            Sonata\AdminBundle\Show\ShowMapper:     # Show
                _copy: Sonata\AdminBundle\Form\FormMapper

#        AcmeBundle\Admin\DemoAdmin:
#            Sonata\AdminBundle\Form\FormMapper:
#                remove: [name, id]
#                add:
#                    id:
#                        type: textarea
#                    gfx_tab:
#                        _options:
#                            description: tab
#                        gfx_group:
#                            _options:
#                                description: with
#                            title: ~
#                            description:
#                                type: textarea
#                                label: Descriiiiiiption
#                                _options:
#                                    translation_domain: fr
#                        gfx_group2:
#                            field2: ~
