blast_core_choice_addChoice:
    path:     blast/ajax/choices/add
    defaults: { _controller: BlastCoreBundle:Choice:addChoice }

blast_core_generate_entity_code:
    path:     blast/core/generateEntityCode
    defaults: { _controller: BlastCoreBundle:EntityCode:generateCode }

blast_admin_search:
    path:     blast/core/search
    defaults: { _controller: BlastCoreBundle:Core:search }